/**
 * Golden-output parity tests: the TS model port must reproduce the Python
 * corrected reference exactly.
 *
 * Fixtures are generated by `scripts/generate_fixtures.py` (run via
 * `npm run generate:fixtures`). Each fixture asserts field-by-field equality
 * on all 24 PeriodResult objects and all three trajectories within a tight
 * tolerance (target 1e-9).
 */

import { describe, expect, it } from 'vitest'
import { readFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'
import { VarroaModelCorrected, PERIOD_DAYS, workerDaughtersEff, rMortBroodless, rMortBroodrearing } from './varroaModel'
import type { Params, PeriodResult } from './varroaModel'

const here = dirname(fileURLToPath(import.meta.url))
const fixtures = JSON.parse(
  readFileSync(join(here, '__fixtures__', 'golden.json'), 'utf-8'),
) as Array<{
  name: string
  config: Record<string, unknown>
  params: Params
  periods: PeriodResult[]
  mite_trajectory: number[]
  wash_trajectory: number[]
  r_trajectory: number[]
}>

const TOL = 1e-9

/** Every numeric field of a PeriodResult, by name. */
const PERIOD_FIELDS: Array<keyof PeriodResult> = [
  'period', 'date', 'frames_bees', 'frames_brood', 'drone_area_frac',
  'adult_bees', 'brood_cells', 'brood_ratio', 'phoretic_days', 'pct_phoretic',
  'pct_in_brood', 'drone_pref_frac', 'pct_mites_drone', 'pct_mites_worker',
  'drone_r_day', 'worker_r_day', 'r_repro', 'r_mortality', 'r_net',
  'mites_start', 'new_mites', 'after_repro', 'after_mort', 'immigration',
  'drift_out', 'drift_net', 'pre_treatment', 'kill', 'mites_end',
  'r_observed', 'pct_cells_invaded', 'wash_count', 'frac_spent', 'crashed',
]

function close(a: number, b: number, tol = TOL): boolean {
  return Math.abs(a - b) <= tol
}

describe('model parity with Python reference', () => {
  it('covers the full scenario battery (9 colonies × 2 hemispheres × 5 immigration × 2 treatments)', () => {
    expect(fixtures.length).toBe(180)
    const names = new Set(fixtures.map((f) => f.name))
    expect(names.size).toBe(180)
  })

  it('ports the params computed properties (log-rates, VSH-effective daughters)', () => {
    const p = fixtures[0]!.params
    expect(workerDaughtersEff(p)).toBeCloseTo(p.worker_daughters * (1 - p.vsh_reduction), 12)
    expect(rMortBroodless(p)).toBeCloseTo(Math.log(1 - p.mort_broodless), 12)
    expect(rMortBroodrearing(p)).toBeCloseTo(Math.log(1 - p.mort_broodrearing), 12)
  })

  it('PERIOD_DAYS matches 365/24', () => {
    expect(PERIOD_DAYS).toBe(365.0 / 24.0)
  })

  for (const fx of fixtures) {
    it(`matches fixture ${fx.name}`, () => {
      const run = new VarroaModelCorrected(fx.config as never).run()

      expect(run.periods).toHaveLength(24)
      expect(run.mite_trajectory).toHaveLength(24)
      expect(run.wash_trajectory).toHaveLength(24)
      expect(run.r_trajectory).toHaveLength(24)

      for (let i = 0; i < 24; i++) {
        const exp = fx.periods[i]!
        const got = run.periods[i]!
        for (const f of PERIOD_FIELDS) {
          const e = exp[f]
          const g = got[f]
          if (typeof e === 'number' && typeof g === 'number') {
            expect(close(e, g), `${fx.name} period ${i + 1} field ${String(f)}`).toBe(true)
          } else {
            expect(g, `${fx.name} period ${i + 1} field ${String(f)}`).toBe(e)
          }
        }
      }

      for (let i = 0; i < 24; i++) {
        expect(close(fx.mite_trajectory[i]!, run.mite_trajectory[i]!), `${fx.name} mite[${i}]`).toBe(true)
        expect(close(fx.wash_trajectory[i]!, run.wash_trajectory[i]!), `${fx.name} wash[${i}]`).toBe(true)
        expect(close(fx.r_trajectory[i]!, run.r_trajectory[i]!), `${fx.name} r[${i}]`).toBe(true)
      }
    })
  }
})

describe('model port behavior (corrected-variant invariants)', () => {
  it('immigration setting is bounds-checked (fix F)', () => {
    expect(() => new VarroaModelCorrected({ immigration_setting: 6 })).toThrow(RangeError)
    expect(() => new VarroaModelCorrected({ immigration_setting: -1 })).toThrow(RangeError)
    expect(() => new VarroaModelCorrected({ immigration_setting: 1.5 })).toThrow(TypeError)
  })

  it('no-bees phoretic edge case is explicit (fix C)', () => {
    const run = new VarroaModelCorrected({ colony_type: 'n', initial_mites: 100 }).run()
    for (const pr of run.periods.slice(0, 6)) {
      expect(pr.adult_bees).toBe(0)
      expect(pr.phoretic_days).toBeNull()
      expect(pr.pct_phoretic).toBeCloseTo(1.0, 12)
      expect(pr.pct_in_brood).toBeCloseTo(0.0, 12)
    }
  })

  it('no-brood sentinel removed (fix D)', () => {
    const run = new VarroaModelCorrected({ colony_type: 'b', initial_mites: 100 }).run()
    for (const pr of run.periods) {
      if (pr.frames_brood === 0) {
        expect(pr.brood_cells).toBe(0)
        expect(pr.brood_ratio).toBe(0)
      }
    }
  })

  it('spent fraction is not capped at 0.99 (fix B)', () => {
    const cohorts = [[100, 90, 80, 70, 60, 50]]
    expect(VarroaModelCorrected._frac_spent(cohorts)).toBe(1.0)
  })

  it('southern hemisphere rotates treatments (fix E)', () => {
    const kills = Array(24).fill(0)
    kills[15] = 0.8 // northern period 16
    const south = new VarroaModelCorrected({
      colony_type: 'd',
      initial_mites: 100,
      southern_hemisphere: true,
      treatment_kills: kills,
    }).run()
    const got = south.periods.map((p) => p.kill)
    // northern period 16 == southern period 4 (source ((p + 11) % 24) + 1)
    expect(got[3]).toBeCloseTo(0.8, 12)
    expect(got.reduce((a, b) => a + b, 0)).toBeCloseTo(0.8, 12)
  })
})
